import { describe, expect, it } from "vitest";
import { valueToString } from "./InputOutput";
import { InputDTO } from "@/types/DTO";

 const mock = {
      input: {
        displayName: "Water Depth",
        description:
          "depth of water. if used as output, it only changes terrain height, not water level!",
        min: 0,
        max: 100,
        ignoreValue: 2147483647,
        valueDisplayNames: [
          "Land (0)",
          "1 deep",
          "2 deep",
          "3 deep",
          "4 deep",
          "5 deep",
          "6 deep",
          "7 deep",
          "8 deep",
          "9 deep",
          "10 deep",
          "11 deep",
          "12 deep",
          "13 deep",
          "14 deep",
          "15 deep",
          "16 deep",
          "17 deep",
          "18 deep",
          "19 deep",
          "20 deep",
          "21 deep",
          "22 deep",
          "23 deep",
          "24 deep",
          "25 deep",
          "26 deep",
          "27 deep",
          "28 deep",
          "29 deep",
          "30 deep",
          "31 deep",
          "32 deep",
          "33 deep",
          "34 deep",
          "35 deep",
          "36 deep",
          "37 deep",
          "38 deep",
          "39 deep",
          "40 deep",
          "41 deep",
          "42 deep",
          "43 deep",
          "44 deep",
          "45 deep",
          "46 deep",
          "47 deep",
          "48 deep",
          "49 deep",
          "50 deep",
          "51 deep",
          "52 deep",
          "53 deep",
          "54 deep",
          "55 deep",
          "56 deep",
          "57 deep",
          "58 deep",
          "59 deep",
          "60 deep",
          "61 deep",
          "62 deep",
          "63 deep",
          "64 deep",
          "65 deep",
          "66 deep",
          "67 deep",
          "68 deep",
          "69 deep",
          "70 deep",
          "71 deep",
          "72 deep",
          "73 deep",
          "74 deep",
          "75 deep",
          "76 deep",
          "77 deep",
          "78 deep",
          "79 deep",
          "80 deep",
          "81 deep",
          "82 deep",
          "83 deep",
          "84 deep",
          "85 deep",
          "86 deep",
          "87 deep",
          "88 deep",
          "89 deep",
          "90 deep",
          "91 deep",
          "92 deep",
          "93 deep",
          "94 deep",
          "95 deep",
          "96 deep",
          "97 deep",
          "98 deep",
          "99 deep",
          "100 deep",
        ],
        discrete: false,
        type: "WATER_DEPTH",
      },
      output: {
        displayName: "Action Filter",
        description:
          "only blocks that pass this filter will be used in following actions.",
        min: 0,
        max: 1,
        ignoreValue: 2147483647,
        valueDisplayNames: ["BLOCK (0)", "PASS (1)"],
        discrete: true,
        type: "INTERMEDIATE_SELECTION",
      },
    };

describe("value to string", () => {
  it("can correctly do an input", () => {
    const toStr = valueToString(mock.input as InputDTO);
    expect(toStr(3)).toEqual("3 deep");
  });
  it("can correctly do an output (ActionFilter)",()=>{
    const toStr = valueToString(mock.output as InputDTO);
    expect(toStr(0)).toEqual("BLOCK (0)");
    expect(toStr(mock.input.ignoreValue)).toEqual("SKIP")

  })
});
