export const PROVIDER_TYPES = {
  ALWAYS: "ALWAYS",
  HEIGHT: "HEIGHT",
  SLOPE: "SLOPE",
  ANNOTATION: "ANNOTATION",
  TERRAIN: "TERRAIN",
  WATER_DEPTH: "WATER_DEPTH",
  WATER_HEIGHT: "WATER_HEIGHT",
  INTERMEDIATE: "INTERMEDIATE",
  INTERMEDIATE_SELECTION: "INTERMEDIATE_SELECTION",
  PERLIN_NOISE: "PERLIN_NOISE",
  SHADOW: "SHADOW",
  VORONOI_NOISE: "VORONOI_NOISE",
  RANDOM_NOISE: "RANDOM_NOISE",
  BLOCK_DIRECTION: "BLOCK_DIRECTION",
  SELECTION: "SELECTION",
  ANNOTATION_SETTER: "ANNOTATION",
  STONE_PALETTE: "STONE_PALETTE",
  BINARY_SPRAYPAINT: "BINARY_SPRAYPAINT",
  BINARY_LAYER: "BINARY_LAYER",
  NIBBLE_LAYER: "NIBBLE_LAYER",
  VANILLA_BIOME: "VANILLA_BIOME",
  DISTANCE_TO_EDGE: "DISTANCE_TO_EDGE",
  TEST: "TEST",
} as const;

export const PROVIDER_DESCRIPTIONS: Record<string, string> = {
  ALWAYS: "Always apply - single value",
  HEIGHT: "Terrain height/elevation",
  SLOPE: "Slope angle",
  ANNOTATION: "Map annotations",
  TERRAIN: "Terrain type/blocks",
  WATER_DEPTH: "Water depth",
  WATER_HEIGHT: "Water height absolute",
  INTERMEDIATE: "Intermediate layer",
  INTERMEDIATE_SELECTION: "Intermediate selection/filter",
  PERLIN_NOISE: "Perlin noise generator",
  SHADOW: "Shadow map",
  VORONOI_NOISE: "Voronoi noise generator",
  RANDOM_NOISE: "Random noise",
  BLOCK_DIRECTION: "Block facing direction",
  SELECTION: "Selection layer",
  STONE_PALETTE: "Stone palette/palette",
  BINARY_SPRAYPAINT: "Binary spray paint layer",
  BINARY_LAYER: "Binary layer",
  NIBBLE_LAYER: "Nibble layer (4-bit)",
  VANILLA_BIOME: "Vanilla biome",
  DISTANCE_TO_EDGE: "Distance to layer edge",
  TEST: "Test input/output",
};
