name: Zip and Upload on Release
# will add default-actions zip folder
on:
  release:
    types: [created, published]
permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Zip the folder
        run: |
          ls defaultActions
          zip -r default-macros.zip ./defaultActions

      - name: Upload zipped folder to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: default-macros.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
